### ISSUE TITLE
Keda로 autoscaling을 해보자.

### ISSUE THREAD

**Issue by hseungjae** [hseungjae/2025#7]
kubectl 설치
```
# kubectl install
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.3/2024-12-12/bin/linux/amd64/kubectl
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.3/2024-12-12/bin/linux/amd64/kubectl.sha256
chmod +x ./kubectl
mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc

aws eks update-kubeconfig --region ap-northeast-2 --name skills-eks-cluster
```
helm 설치
```
# helm install 
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh
```
keda 설치
```
# KEDA install
helm repo add kedacore https://kedacore.github.io/charts
helm repo update
helm install keda kedacore/keda --namespace keda --create-namespace
```
keda 설치하면 pod가 새로 생성됨 
![Image](https://github.com/user-attachments/assets/5fbf8c9d-0b39-44d8-939c-efb7c06be061)

nginx 배포파일을 배포해준다.

오토 스케일링 배포 파일 만든 후 배포해준다.
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-scaledobject
  namespace: test
spec:
  scaleTargetRef:
    name: nginx-deployment
  pollingInterval: 15
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: https://sqs.ap-northeast-2.amazonaws.com/932169417000/skills-sqs
      queueLength: "10"
      awsRegion: "ap-northeast-2"
      identityOwner: operator
```

오류가난다?
노드 인스턴스 IMDSv2를 Optional로 변경한다.

![Image](https://github.com/user-attachments/assets/2537feac-1d6a-4f0a-9973-d77f28308286)

test 방법
```
QUEUE_URL="https://sqs.<region>.amazonaws.com/<account-id>/<queue-name>"
for i in {1..20}; do
    aws sqs send-message --queue-url "$QUEUE_URL" --message-body "Message $i" && echo "Sent $i" || echo "Fail $i" >&2
done

```
> 참고자료 👍 
https://docs.aws.amazon.com/ko_kr/eks/latest/userguide/install-kubectl.html 
https://helm.sh/docs/intro/install/
https://keda.sh/docs/2.9/deploy/
